msg: '&6[&5Channel 11 news&6] &9%announcer% &7presenting for channel 11 news. &2%player% &7was found dead. Police have ruled it a homicide. Police have identified &4%killer% &7as a suspect'
msgMobWithoutName: '&6[&5Channel 11 news&6] &9%announcer% &7presenting for channel 11 news. &2%player% &7was found dead. Police have ruled it a homicide. Police have identified a &c%killer% &7as a suspect'
msgMobWithName: '&6[&5Channel 11 news&6] &9%announcer% &7presenting for channel 11 news. &2%player% &7was found dead. Police have ruled it a homicide. Police have identified &c&o%killer% &r&7as a suspect'
msgNoKiller: '&6[&5Channel 11 news&6] &9%announcer% &7presenting for channel 11 news. &2%player% &7was found dead. Police have ruled it a suicide'
msgKilledByCustom: '&6[&5Channel 11 news&6] &9%announcer% &7presenting for channel 11 news. &2%player% &7was found dead. They appear to have been killed by &e&o%item%&r&7. Police have ruled it a homicide. Police have identified &4%killer% &7as a suspect. '
announcers: 
  - 'Kylie Jenner'
  - 'Kanye West'
  - 'Howard Stern'
  - 'Dwayne Johnson'